services:
     app:
       build:
         context: .
         dockerfile: Dockerfile
       env_file:
         - ./.env.test
       ports:
         - "8080:8080"
       depends_on:
         - db

     db:
       image: postgres:latest
       restart: always
       environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: 265714
         POSTGRES_DB: test_oxo_db
       ports:
         - "5432:5432"